### ISSUE TITLE
NullPointerException after switch layout

### ISSUE THREAD

**Issue by lavendersk** [gjiazhe/LayoutSwitch#3]
先切换layout 然后滑动recyclerView 再点切换 再滑动报错
java.lang.NullPointerException: java.lang.NullPointerException
                                                                              at com.gjiazhe.layoutswitch.ItemAdapter.onBindViewHolder(ItemAdapter.java:47)
                                                                              at

**Comment by wuyifengWYF** [comment]
Switch layout first, then slide recyclerView, then switch again, then slip the error
at com.gjiazhe.layoutswitch.ItemAdapter.onBindViewHolder(ItemAdapter.java:47)
![image](https://cloud.githubusercontent.com/assets/16146763/26614053/8d14aa80-45f0-11e7-80a1-64987d819df2.png)
